config/routes.rb
Rails.application.routes.draw do
  #used to create,new,update users urls
  #rake routes  
  resources :glsusers
  resources :notes
  resources :categories #, except: [:destroy]
  resources :articles
  resources :addresses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #route URL localhost:port/pages/home to controller 'pages' method 'home'
  #get 'pages/home', to: 'pages#home'
  
  #route URL localhost:port/  root to controller 'pages' method 'home' 
  root 'pages#home'
  
  #route URL localhost:port/pages/about to controller 'pages' method 'about'
  #get 'pages/about', to: 'pages#about'
  get 'about', to: 'pages#about'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'


  
end

app/views/layouts/_footer.html.erb
<div class="container">
	<footer>
		<small>Copywrite &copy; <a href="https://www.udemy.com">Udemy</a></small>	
		<nav>
			<ul>
				<li><%= link_to "about", about_path%></li>
			</ul>
		</nav>
	</footer>
</div>

app/views/layouts/_message.html.erb
<div class="row">
	<div class="col-xs-offset-2 col-xs-8">
		<% flash.each do |name,msg|%>
			<div class='alert alert-<%= "#{name}"%>'>
				<a href="#" class="close" data-dismiss="alert">&#215</a>
				<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)%>
			</div>
		<% end %>
	</div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to  image_tag("User_icon_2.svg.png", :width=> "50px",height: "50px"), root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <li><%= link_to "Articles", articles_path%></li>
        <li><%= link_to "Users", glsusers_path%></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Users Actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Create a new user", new_glsuser_path if current_glsuser && current_glsuser.admin? %></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
         <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu">
           <li><%= link_to "All Categories", categories_path%></li>
            <% Category.all.each do |category|%>
              <li>
                <%= link_to "#{category.name}", category_path(category) %>
              </li>
            <% end %>
            <li role="separator" class="divider"></li>
            <li>
              <%= link_to "Create a new category", new_category_path if logged_in? && current_glsuser.admin? %>
            </li>
           </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "log out", logout_path, method: :delete%></li>
        <% else %>
          <li><%= link_to "log in ", login_path%></li>
           <li><%= link_to "sign up ", new_glsuser_path%></li>
        <% end %>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile <%= "admin" if current_glsuser.admin? %><span class="caret"></span></a>
            <ul class="dropdown-menu">
        
              <li><%= link_to "Edit your profile", edit_glsuser_path(current_glsuser) %></li>
              <li><%= link_to "View your profile", glsuser_path(current_glsuser) %></li>
           
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
         <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <%= render '/layouts/navigation'%>
  <%= render '/layouts/message'%>
  <div class="container  main-content">
    <%= yield %> 
  </div>
  <%= render '/layouts/footer'%>
  </body>
</html>